name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: PR Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Lint/Test/Build
        run: yarn rebirth
